### ISSUE TITLE
Adapter Error

### ISSUE THREAD

**Issue by Starter4711** [fungus75/ioBroker.zoe2#22] opened 2021-02-18 14:07 UTC
Hello, adapter terminates without reason?
no Objects are shown.
<img width="871" alt="Bildschirmfoto 2021-02-18 um 15 05 37" src="https://user-images.githubusercontent.com/15359915/108368565-e6085300-71fa-11eb-87d3-5c1b2958603c.png">
<img width="1261" alt="Bildschirmfoto 2021-02-18 um 15 39 59" src="https://user-images.githubusercontent.com/15359915/108372992-b27bf780-71ff-11eb-9dab-3c6260d499b5.png">
<img width="1167" alt="Bildschirmfoto 2021-02-18 um 15 39 55" src="https://user-images.githubusercontent.com/15359915/108372997-b3ad2480-71ff-11eb-91fe-96f380db5cd2.png">

**Comment by fungus75** [comment] 2021-02-23 10:15
Looks like this is a duplicate of https://github.com/fungus75/ioBroker.zoe2/issues/20

General: please update to the most recent version of the adapter.
After updating, please go to the settings/configuration-screen, change any value (so that the SAVE-Button becomes active), change the value back and press save. Some versions require new config parameters and raise an error otherwise.

**Closed by fungus75** 2021-02-23 10:15 UTC
